name: Update Remote Index

# Controls when the action will run. Triggers the workflow on a custom dispatch request
on:
  repository_dispatch:
    types: update-index

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "execute"
  execute:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: '3.1.x'

    # Runs commands
    - run: dotnet tool install -g dotnet-script
    - shell: sh
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: dotnet script Scripts/UpdateRemoteIndexFromSpreadsheet.csx
    - run: git config user.name "github-actions"
    - run: git add RemoteIndex.xml
    - run: git commit -m "Update Remote Config"
    - run: git push https://${{ secrets.GITHUB_TOKEN }}@github.com/Zombeaver/PCSX2-Configs.git
